---
title: "RWorksheet2_PAMA"
author: "Miko Pama"
date: "2023-11-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r 1a}
#1. Generate a sequence from -5 to 5.
#output: [1] 1 2 3 4 5 6 7 8 9 10 11
#If i use the : operator, the output will be 1 to 11, but if i change:

sequence <- seq(-5:5)
sequence
```

```{r 1b}
#b. What will be the value of x?
#Value of will be a sequence from 1 to 7
x <- 1:7
x
```

```{r 2}
#2. Create a vector using seq() function.
#Output: [1] 1.0 1.2 1.4 1.6 1.8 2.0 2.2 2.4 2.6 2.8 3.0
#The numbers are sequence but in 0.2 interval.
seq(1, 3, by=0.2)
```

```{r 2a}
Vec<- seq(1,3,0.2)
Vec
```

```{r 3}
#3. Create a vector with the age of the factory workers.

age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,
         22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,
         24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,
         18.)
age
```

```{r 3a}
age[3]
```

```{r 3b}
workerAge <- age[c(2,4)]
workerAge
```

```{r 3c}
workerAge1 <- age[-c(4,12)]
workerAge1
```

```{r 4}
x <- c("first" = 3, "second" = 0, "third" = 9)
print(x)
```

```{r 4a}
selectedE <- x[c("first", "third")]
print(selectedE)
# It selectively accesses and displays the elements "first" and "third" from the vector, showing their corresponding values.
```

```{r 5}
x2<- c(-3:2)
x2
# Instead of -2 in the second element it changed into 0.
```

```{r 5a}
x2[2] <- 0
x2
```

```{r 6a}
#6. a. Create a data frame for month, price per liter (php) and purchase and purchase-quantity (liter). Write the R scripts and its output.
diesel <- data.frame(
  month = c("Jan","Feb","March","April","May","June"),
  price_per_liter = c(52.50,57.25,60.00,65.00,74.25,54.00),
  purchase_quantity = c(25,30,40,50,10,45)

)
diesel
```

```{r 6b}
#b. Calculate the weighted mean of fuel expenditure
average_expenditure <- weighted.mean(diesel$price_per_liter, diesel$purchase_quantity)

#Print the average fuel expenditure
average_expenditure
```

```{r 7a}
#7.a. Create a vector data with 7 elements.

rivers
```

```{r 7c}
data <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers),sd(rivers), min(rivers), max(rivers))
data
```

```{r 8a}
#8. Create vectors according to the above table.
#a.
power_ranking <- c(1:25)
celebtrity_names <-c("Tom Cruise", "Rolling Stone", "Oprah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", 
"Cast of Sopranos", "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas","Elton John", "David Letterman", "Phil Mickelson", "J.K Rowling", "Bradd Pitt", "Peter Jackson", "Dr. Phil McGraw", "Jay   Lenon", "Celine Dion", "Kobe Bryant" )
pay <- c(67,90,225,110,90,332,302,41,52,88,55,44,55,40,233,34,40,47,75,25,39,45,32,40,31)
PowerRanking <- data.frame(power_ranking, celebtrity_names, pay)
PowerRanking
```

```{r 8b}
#b. Modify the power ranking and pay of J.K. Rowling. Change power ranking to 15 and pay to 90.

power_ranking[19] <- 15
power_ranking 
pay[19] <- 90
pay
```


```{r 8c}
#c Create an excel file from the table above.

library(readr)
PowerRanking <- read_csv("/cloud/project/RWorksheet_Pama#2.rmd/PowerRanking.csv")
PowerRanking
```

```{r 8d}
subset_data <- PowerRanking[10:20, ]
save(subset_data, file = "Ranks.RData")
print(subset_data)
```

```{r 9a}
library(readxl)
hotels_vienna <- read_excel("/cloud/project/RWorksheet_Pama#2.rmd/hotels vienna.xlsx")
hotels_vienna
```

```{r 9b}
dimensions <- dim(hotels_vienna)
dimensions
```

```{r 9c}
selected_columns <- hotels_vienna[, c("country", "neighbourhood", "price", "stars", "accommodation_type", "rating")]
head(selected_columns, n = nrow(selected_columns))
```
```{r 9d}
save(selected_columns, file = "new.RData")
```

```{r 9e}
load("new.RData")
head(selected_columns)
tail(selected_columns)
```

```{r 10a}
Vegetables <- list("lettuce","pumpkin","squash","carrot", "cucumber", "spinach", "leek", "lettuce","mushroom","turnip")
Vegetables
```

```{r 10b}
vegetablesList <- append(Vegetables,c("eggplant","peas"),after=10)
vegetablesList
```

```{r 10c}
Veggies <- append(vegetablesList,c("bitter gourd","moringa","cabbage"," yam"),after=5)
Veggies
```

```{r 10d}
NewVeggies<- Veggies[c(-5,-10,-15)]
NewVeggies

length(NewVeggies)
```
